"""Add description to MeetingRoom

Revision ID: 4dde2fc4f31d
Revises: e86cebff1a8c
Create Date: 2025-11-29 12:33:56.872668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dde2fc4f31d'
down_revision: Union[str, Sequence[str], None] = 'e86cebff1a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
