"""Fix

Revision ID: 7c9563d8070c
Revises: fd6e8293a56c
Create Date: 2025-11-29 23:13:04.095380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9563d8070c'
down_revision: Union[str, Sequence[str], None] = 'fd6e8293a56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('to_reserve', sa.DateTime(), nullable=True))
    op.drop_column('reservation', 'to_reserver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('to_reserver', sa.DATETIME(), nullable=True))
    op.drop_column('reservation', 'to_reserve')
    # ### end Alembic commands ###
